### DISCUSSION TITLE
Should the state class for "Current Layer" and "Total Layer Count" be MEASUREMENT?

### DISCUSSION THREAD

**Discussion by akoebbe** [greghesp/ha-bambulab#570] [General]
Love the integration! I was hoping to see a line graph when viewing the Current Layer sensor, so I could see which layer took the longest, but it doesn't look like the layer sensors are set to be measurements and are treated as string states. Any reason for this or can we switch these by adding the following to the layer definitions.

```
state_class=SensorStateClass.MEASUREMENT
```

**Comment by akoebbe** [comment]
I decided to just give it a try and it does work. However, I am getting blips where the measurement goes to zero or some float near zero. Not sure what that's about.

![image](https://github.com/user-attachments/assets/97bb6142-1207-4e15-baef-33458dac94ec)

**Comment by nzrutman** [comment]
Yes, these should be changed to measurement. If not, the history storage is expensive as strings, and you don't get nice graphs. Similarly, the time values should be changed to `device_class: timestamp` for proper handling in Lovelace cards. This can be easily done in customize.yaml:
```
sensor.mike_end_time:
  device_class: timestamp
sensor.mike_start_time:
  device_class: timestamp
sensor.mike_current_layer:
  state_class: measurement
sensor.mike_total_layer_count:
  state_class: measurement
```
but obviously should be added to the code directly instead as you say.
