### ISSUE TITLE
[Bug] Bambu Lab: Load filament action doesn't trigger

### ISSUE THREAD

**Issue by greghesp** [greghesp/ha-bambulab#1055]
### Home Assistant Version

2025.2.0

### Bambu Lab Integration Version

main branch

### Describe the bug

```
action: bambu_lab.load_filament
data:
  tray: 1
target:
  device_id: 9a4f479aec86dec73881670d1c067c0f
```

Does not trigger any filament loading

### To Reproduce

Go to UI and try a load_filament action

### Expected Behaviour

Filament loads

### What device are you using?

X1C

### Diagnostic Output

```shell
-
```

### Log Extracts

```shell

```
