### ISSUE TITLE
action: bambu_lab.print_project_file with folders?

### ISSUE THREAD

**Issue by TheBasedDoge** [greghesp/ha-bambulab#1090]
Is it possible to use action: bambu_lab.print_project_file with folders? 

My action is below:
```
 action: bambu_lab.print_project_file
      data:
        filepath: /_S2000/Bracket.gcode.3mf
        plate: 1
        use_ams: false
        timelapse: false
        bed_leveling: true
        flow_cali: false
        vibration_cali: true
        layer_inspect: false
        ams_mapping: "0"
      target:
        device_id:
```

however, when I run it, I get the following back from my printer - **Print Error [83935248 / 500c010]: MicroSD Card error: please reinsert, format or replace it.**

I also use this project with my printers, and I am able to use folders with it, so I would like to keep everything consistent - https://github.com/TFyre/bambu-farm
