### ISSUE TITLE
[Bug] Print Control Card Layout on Mobile

### ISSUE THREAD

**Issue by sabaatworld** [greghesp/ha-bambulab#1129]
### Home Assistant Version

2025.3.1

### Bambu Lab Integration Version

v2.1.7

### Describe the bug

As seen in the attached image below, the print control card does not render properly on mobile. The buttons are not evenly spaced and its causing the whole dashboard tab to have a scroll bar.

![Image](https://github.com/user-attachments/assets/0de3ad2b-c8d8-43ae-abd1-51634ba4c5d3)

### To Reproduce

1. Add print control card to dashboard.
2. View in Home Assistant app.

### Expected Behaviour

1. Buttons should be spaced out evenly.
2. Dashboard should not have a scroll left-right behavior.

### What device are you using?

P1S

### Diagnostic Output

```shell
N/A. This is a layout issue.
```

### Log Extracts

```shell
N/A. This is a layout issue.
```

### Other Information

N/A

**Comment by Hans-Solo-Dolo** [comment]
Same issue [here](https://github.com/greghesp/ha-bambulab/issues/1111)

**Comment by eodabas** [comment]
I've fixed it using the following workaround:

```yaml
type: custom:ha-bambulab-print_control-card
printer: 2706918xxxxxxxxxxxxae2602210d3b
grid_options:
  columns: full
  rows: auto
card_mod:
  style: |
    div.control-container {
      width: 100%;
      overflow: hidden;
    }
    div.buttons-container {
      gap: 0px
    }
```

**Comment by Hans-Solo-Dolo** [comment]
> I've fixed it using the following workaround:

For some reason, that fix wasn't working for me so I did it with 

```
grid_options:
  columns: 4
  rows: auto
  width: 100%
```

and 

```
card_mod:
  style: |
    ha-card {
      padding: 8px 10px !important; /* Keeps normal top & bottom padding */
    }
```
