### ISSUE TITLE
[Bug] Print Control Card Height is slightly too tall

### ISSUE THREAD

**Issue by Samywamy10** [greghesp/ha-bambulab#1165]
### Home Assistant Version

2025.3.3

### Bambu Lab Integration Version

v2.1.8

### Describe the bug

![Image](https://github.com/user-attachments/assets/7c51b1cd-6758-445e-8ddb-f5eeefb721ea)

The height of the print control card is slightly taller than 1 grid row, meaning it doesn't line up with 1 height cards.

### To Reproduce

Bring in a print control card e.g.'
```
type: custom:ha-bambulab-print_control-card
printer: 75138cbdd8a000e2d81911976a1a0535
grid_options:
  columns: 12
  rows: 1
```

And put it next to something else with 1 row

### Expected Behaviour

It takes up just 1 row height

### What device are you using?

P1P

### Diagnostic Output

```shell
n/a
```

### Log Extracts

```shell

```
