### ISSUE TITLE
[Feature?] Allow filtering trigger events based on code

### ISSUE THREAD

**Issue by ndom91** [greghesp/ha-bambulab#1183]
First of all, thanks for this amazing integration and the significant number of updates / PRs lately!

I have an automation that triggers on the device "Print Error" event. Looking at the trace, that looks like this:

```
trigger:
  id: '0'
  idx: '0'
  alias: null
  platform: device
  event:
    event_type: bambu_lab_event
    data:
      device_id: abc123
      name: bedroom_01
      type: event_print_error
      code: 0300_400C
      error: Printing was cancelled.
    origin: LOCAL
    time_fired: '2025-03-21T12:25:28.449288+00:00'
```

And what I'd like to do is only allow this to continue if the `event.data.code` isn't one of a list of white or black -listed codes.

For example, the printer error event fires for many [events](https://forum.bambulab.com/t/poll-bambu-lab-please-provide-a-complete-list-of-error-codes/17232/7) that aren't errors in my opinion, like "0300400C Print was Cancelled". 

What I currently do is have the `And if..` section of the automation full of checks on other sensors like the current print stage, etc. but this isn't very reliable. 

Maybe there's a way to do this in homeassistant already that I just don't know? Happy for any tips 🙏

**Comment by ndom91** [comment]
Ahh okay I think I got it working

![Image](https://github.com/user-attachments/assets/1ab2965b-b5db-4669-8afb-992a8f70f7b0)

i.e.

```yaml
alias: Bambu A1 - Print Error
description: ""
triggers:
  - device_id: 6f8d35da05e30175ce58f9b4ab37da33
    domain: bambu_lab
    type: event_print_error
    trigger: device
conditions:
  - condition: template
    value_template: >-
      {# Codes: https://forum.bambulab.com/t/poll-bambu-lab-please-provide-a-complete-list-of-error-codes/17232/7 #}

      {{ trigger.event.data['code'] not in ['0300_400C'] }}
```
