### ISSUE TITLE
[Bug] Squished Simple display card on v2.1.20 (when viewing inside a Bubble Card)

### ISSUE THREAD

**Issue by BirbByte** [greghesp/ha-bambulab#1381]
### Home Assistant Version

2025.6.1

### Bambu Lab Integration Version

v2.1.20

### Describe the bug

This issue presents itself when putting the card inside of a Bubble Card. (https://github.com/Clooos/Bubble-Card)

On the previous version, the 'Simple' card view looked fine, only sometimes text would be a little overlapped. Understandable since using a bubble card will slightly reduce the overall width this bambu card is visible.

Now when I view a 'simple' card on my phone screen (iPhone 16 Pro) it's not possible to see any valuable information. I've also attached a screenshot of what it looks like from a web browser, but still slightly cut off.

![Image](https://github.com/user-attachments/assets/cf103fc2-35af-45e2-979d-8ddf29ba6570)

<img width="603" alt="Image" src="https://github.com/user-attachments/assets/2c096aa2-1a21-4d7d-8fbb-1bbc14d9fdf2" />
<img width="603" alt="Image" src="https://github.com/user-attachments/assets/2e4b217c-f325-47b7-a22c-84d526e154f8" />
<img width="603" alt="Image" src="https://github.com/user-attachments/assets/0e381f5f-8a2f-4683-95cf-88c760c8bfaf" />
<img width="603" alt="Image" src="https://github.com/user-attachments/assets/d3c21c65-b89d-4251-9ea7-31a7a9416f49" />

### To Reproduce

Create a bubble card "view".

(To make this simple, I've pasted in my whole code for my card which includes the "graphic card style, live camera, and the problematic "simple" card style)

```
type: vertical-stack
cards:
  - type: custom:bubble-card
    card_type: pop-up
    hash: "#3d-printer"
    name: 3D Printer
    icon: mdi:printer-3d-nozzle
    show_header: true
    scrolling_effect: false
    force_icon: false
    show_icon: true
    show_name: true
    background_update: false
    close_on_click: false
    bg_opacity: "40"
    slide_to_close_distance: "400"
    bg_blur: "10"
    card_layout: normal
    styles: |-
      .bubble-close-button:active, .bubble-close-button:hover {
        color: red !important;
        transition: 0.1s ease;
      }
    tap_action:
      action: none
    double_tap_action:
      action: none
    hold_action:
      action: none
    margin: 7px
    margin_top_mobile: 0px
    sub_button: []
    button_action:
      tap_action:
        action: none
      double_tap_action:
        action: none
      hold_action:
        action: none
  - type: custom:ha-bambulab-print_status-card
    printer: d19418e526b3597e4404e2611015acd4
    style: graphic
    custom_light: light.bambu_chamber_lightstrip_light
    custom_power: switch.3d_printing_switch
  - show_state: false
    show_name: false
    camera_view: auto
    fit_mode: cover
    type: picture-entity
    entity: camera.x1c_00m09a372400248_camera
    image: https://demo.home-assistant.io/stub_config/bedroom.png
  - type: custom:ha-bambulab-print_status-card
    printer: d19418e526b3597e4404e2611015acd4
    style: simple
    custom_light: light.bambu_chamber_lightstrip_light
    custom_power: switch.3d_printing_switch
```

### Expected Behaviour

I expected for it to show the same as the last version. Or ideally, maybe the card to be scaled slightly smaller in order to fit in the desired width of my display/card.

### What device are you using?

X1C

### Diagnostic Output

```shell
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2025.6.1",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.13.3",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Pacific/Auckland",
    "os_name": "Linux",
    "os_version": "6.6.74-haos-raspi",
    "supervisor": "2025.05.5",
    "host_os": "Home Assistant OS 15.2",
    "docker_version": "28.0.4",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "hacs": {
      "documentation": "https://hacs.xyz/docs/use/",
      "version": "2.0.5",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "echonetlite": {
      "documentation": "https://www.github.com/scottyphillips/echonetlite_homeassistant",
      "version": "3.8.7",
      "requirements": [
        "pychonet==2.6.15"
      ]
    },
    "bhyve": {
      "documentation": "https://github.com/sebr/bhyve-home-assistant/blob/main/README.md",
      "version": "3.2.5",
      "requirements": []
    },
    "iphonedetect": {
      "documentation": "https://github.com/mudape/iphonedetect",
      "version": "2.4.1",
      "requirements": [
        "pyroute2==0.7.5"
      ]
    },
    "bambu_lab": {
      "documentation": "https://github.com/greghesp/ha-bambulab",
      "version": "2.1.20",
      "requirements": [
        "beautifulsoup4"
      ]
    },
    "tapo": {
      "documentation": "https://github.com/petretiandrea/home-assistant-tapo-p100",
      "version": "3.2.0",
      "requirements": [
        "plugp100==5.1.4"
      ]
    },
    "browser_mod": {
      "documentation": "https://github.com/thomasloven/hass-browser_mod/blob/master/README.md",
      "version": "2.4.0",
      "requirements": []
    },
    "fontawesome": {
      "documentation": "https://github.com/thomasloven/hass-fontawesome",
      "version": "2.2.3",
      "requirements": []
    },
    "smartthinq_sensors": {
      "documentation": "https://github.com/ollo69/ha-smartthinq-sensors",
      "version": "0.41.1",
      "requirements": [
        "pycountry>=23.12.11",
        "xmltodict>=0.13.0",
        "charset_normalizer>=3.2.0"
      ]
    }
  },
  "integration_manifest": {
    "domain": "bambu_lab",
    "name": "Bambu Lab",
    "codeowners": [
      "greghesp",
      "AdrianGarside"
    ],
    "config_flow": true,
    "dependencies": [
      "device_automation",
      "ffmpeg",
      "frontend",
      "http",
      "lovelace",
      "mqtt",
      "websocket_api"
    ],
    "documentation": "https://github.com/greghesp/ha-bambulab",
    "iot_class": "local_push",
    "issue_tracker": "https://github.com/greghesp/ha-bambulab/issues",
    "requirements": [
      "beautifulsoup4"
    ],
    "ssdp": [
      {
        "st": "urn:bambulab-com:device:3dprinter:1"
      }
    ],
    "version": "2.1.20",
    "is_built_in": false,
    "overwrites_built_in": false
  },
  "setup_times": {
    "null": {
      "setup": 2.2795997210778296e-05
    },
    "fd6e23c5af5255a8ef0d1e1035000982": {
      "wait_import_platforms": -1.7058607099970686,
      "config_entry_setup": 1.7777859729976626,
      "config_entry_platform_setup": 0.012765901003149338
    }
  },
  "data": {
    "config_entry": {
      "created_at": "1970-01-01T00:00:00+00:00",
      "data": {
        "device_type": "X1C",
        "serial": "**REDACTED**"
      },
      "discovery_keys": {},
      "disabled_by": null,
      "domain": "bambu_lab",
      "entry_id": "fd6e23c5af5255a8ef0d1e1035000982",
      "minor_version": 1,
      "modified_at": "2025-06-23T09:56:07.584508+00:00",
      "options": {
        "access_code": "**REDACTED**",
        "auth_token": "",
        "email": "",
        "enable_camera": true,
        "host": "192.168.178.69",
        "local_mqtt": true,
        "name": "X1C",
        "region": "",
        "usage_hours": 1352.7499999999989,
        "username": ""
      },
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "subentries": [],
      "title": "**REDACTED**",
      "unique_id": null,
      "version": 2
    },
    "pushall": {
      "print": {
        "command": "extrusion_cali_get",
        "filament_id": "",
        "filaments": [],
        "nozzle_diameter": "0.4",
        "reason": "fila_device_extrusion_get_all error",
        "result": "fail",
        "sequence_id": "21430"
      }
    },
    "get_version": {
      "info": {
        "command": "get_version",
        "module": [
          {
            "flag": 15,
            "hw_ver": "N/A",
            "name": "ota",
            "new_ver": "01.09.01.00",
            "sn": "**REDACTED**",
            "sw_ver": "01.08.02.00"
          },
          {
            "flag": 4,
            "hw_ver": "AMS08",
            "name": "ams/0",
            "new_ver": "00.00.06.75",
            "sn": "**REDACTED**",
            "sw_ver": "00.00.06.44"
          },
          {
            "flag": 0,
            "hw_ver": "MC07",
            "name": "mc",
            "sn": "**REDACTED**",
            "sw_ver": "00.00.27.26"
          },
          {
            "flag": 0,
            "hw_ver": "SMC01",
            "name": "sm",
            "sn": "**REDACTED**",
            "sw_ver": "00.00.27.26"
          },
          {
            "flag": 0,
            "hw_ver": "TH09",
            "name": "th",
            "sn": "**REDACTED**",
            "sw_ver": "00.00.07.12"
          },
          {
            "flag": 0,
            "hw_ver": "AP05",
            "name": "ap",
            "sn": "**REDACTED**",
            "sw_ver": "00.00.32.39"
          }
        ],
        "sequence_id": "21186"
      }
    }
  }
}
```

### Log Extracts

```shell

```
