### ISSUE TITLE
[Feature] Notifications template

### ISSUE THREAD

**Issue by TheUnlimited64** [greghesp/ha-bambulab#1391]
### Describe the feature

I really like that I'm able to integrate my lan mode bambulab printer into HA, but I'm missing a crucial feature of the bambulab Handy app.

I often miss when filament runs out because there's currently no notifications available (at least that I know of).

So I would like (if possible) a blueprint or something like this, that would enable me to get notifications on my smartphone for various things like filament ran out, print error, print finished etc.

### What device is this for?

P1P

**Comment by AdrianGarside** [comment]
You can currently set that up manually. I have that. I don't know if that can be easily templatized though.

**Comment by TheUnlimited64** [comment]
I'm a bit overwhelmed by what to trigger an notification for and what sensors to use.

I believe it can be templatized easily. Maybe you can share yours and I try to make a template out of it using a bit of AI?

**Comment by AdrianGarside** [comment]
```
alias: Print finished
description: ""
triggers:
  - device_id: 78189ca5fe5e1c28683002a8cdacb55d
    domain: bambu_lab
    type: event_print_finished
    trigger: device
    id: P1P
conditions: []
actions:
  - data:
      message: Print finished on {{trigger.event.data.name}}
    action: notify.mobile_app_adrians_iphone
```
