### ISSUE TITLE
[Feature] <More device trigger option>

### ISSUE THREAD

**Issue by L1cardo** [greghesp/ha-bambulab#292]
### Describe the feature

It would be nice to have all the options in device trigger, like "current_stage" and all the other staff.
I now use `state` as trigger to automatically go into ludicrous mode if the task name has "fast".

![image](https://github.com/greghesp/ha-bambulab/assets/33802186/b492ade3-1de3-4547-81fd-fd50fdddff16)

```
alias: A1 Mini auto ludicrous mode
description:  if task name has “fast”，then go into ludicrous mode
trigger:
  - platform: state
    entity_id:
      - sensor.a1_mini_current_stage
    to: printing
condition:
  - condition: template
    value_template: "{{ 'fast' in states('sensor.a1_mini_task_name') }}"
action:
  - device_id: cxxxxxxxxxxxx7
    domain: select
    entity_id: fxxxxxxxxxxxxxx3
    type: select_option
    option: ludicrous
mode: single
```

### What device is this for?

A1 Mini
