### ISSUE TITLE
[Bug] Cover image doesn't update when it should.

### ISSUE THREAD

**Issue by renedis** [greghesp/ha-bambulab#375]
### Describe the feature

Since HA 2023.07 there is already an image overview available as an entity.

All i did was add these lines to the YAML:

```
      - type: image
        entity: image.x1c_<BAMBU serial>_cover_image
        style:
          top: 50%
          left: 50%
```

<img width="456" alt="Scherm­afbeelding 2023-12-30 om 20 53 22" src="https://github.com/greghesp/ha-bambulab/assets/10537789/f2f926d6-61dd-4527-974d-c75bd159f4fd">

which shows the STL/3MF in the center of the X1C picture without the use of node-red. I did not do any ha-card styling, but this would be possible to.

Only thing is that the image does not get updated untill the print is completed. Is it possible to add a trigger to update the image (image.py?) on start of print (when state goes to "running" for example).

As a test I reloaded the integration. And yes, then it will update the image.

I have a X1C but my best guess is that this applies to all Bambu Lab printers.

### What device is this for?

X1C

**Comment by renedis** [comment]
For now i've got a work around with an automation:

```
- alias: 'Reload Bambu Lab integration for image update'
  trigger:
    platform: state
    entity_id: sensor.x1c_<BAMBU serial>_current_stage
    to: 'heatbed_preheating'
  action:
    service: homeassistant.reload_config_entry
    data:
      entry_id: "cf00de00ee0f0000b000c00000000be9" #entry ID of the integration
```

This works, but I do need to manually refresh the webpage to update the image in lovelace.

**Comment by renedis** [comment]
started to digging some more..

looks like:
```
    @property
    def image_last_updated(self) -> datetime | None:
        """The time when the image was last updated."""
        return self.coordinator.get_model().cover_image.get_last_update_time()
```

Isn't working?

**Comment by AdrianGarside** [comment]
Which version are you running? This should be fixed in v2.0.3

**Comment by renedis** [comment]
Was on v2.0.2, just updated to v2.0.3
Didn't checked for a new version, my bad.

Can confirm that date-stamp now works and image gets updated.

Adding below to the yaml works 100% (even used filament color is correct in the image)

```
      - type: image
        entity: image.x1c_<BAMBU serial>_cover_image
        style:
          top: 50%
          left: 50%
```

Maybe the generating script of https://www.wolfwithsword.com/bambulab-home-assistant-dashboard/ can be updated to, to reflect this update. @WolfwithSword 

Thanks for the hard work on this integration.
