### ISSUE TITLE
[Bug] Target Bed and Nozzle Temperature not setting

### ISSUE THREAD

**Issue by Samywamy10** [greghesp/ha-bambulab#818]
### Home Assistant Version

2024.12.5

### Bambu Lab Integration Version

v2.0.38

### Describe the bug

When I set either a target bed or target nozzle temperature, the action succeeds with no error but the target temperatures aren't actually set.

### To Reproduce

Run this action:
```
action: number.set_value
data:
  value: "80"
target:
  entity_id:
    - number.samlab_printer_bed_target_temperature # Insert your bed target entity here
    - number.samlab_printer_nozzle_target_temperature # Insert your nozzle target entity here
```

### Expected Behaviour

- I can see the set target updated in the number entities state
- I can see the target in the Bambu Handy or Bambu Studio apps
- The bed and nozzle current temperature moves towards the targets

### What device are you using?

P1S

### Diagnostic Output

[config_entry-bambu_lab-01JCFV3Q3NTZHBG9519QGWP40W.json](https://github.com/user-attachments/files/18286845/config_entry-bambu_lab-01JCFV3Q3NTZHBG9519QGWP40W.json)

### Log Extracts

```shell
2025-01-01 18:37:55.226 DEBUG (SyncWorker_0) [custom_components.bambu_lab.pybambu] {'print': {'sequence_id': '0', 'command': 'gcode_line', 'param': 'M104 S80\n'}}
2025-01-01 18:37:55.226 DEBUG (SyncWorker_0) [custom_components.bambu_lab.pybambu] Sent {'print': {'sequence_id': '0', 'command': 'gcode_line', 'param': 'M104 S80\n'}} to topic device/01P00C4A0500083/request
```
