### ISSUE TITLE
NAME does not support templating (or I am doing it wrong)

### ISSUE THREAD

**Issue by RobertoCravallo** [greghesp/ha-bambulab#837]
### Describe the feature

Under HOME ASSISTANT I would really like to be able to use this:

**name: "{{ states('sensor.p1s_name_der_aufgabe') }}"**

This does not seem to work. I would really like to be able to show the name of the project in the overlay. Maybe there is a way I missed?

![Image](https://github.com/user-attachments/assets/4a286d1f-053a-4e2d-8a0a-9de87de25b4f)

### What device is this for?

P1S

**Comment by steveneaston** [comment]
Try using the "Picture Elements" card with the "State Label" entity instead. This lets you add one or more entities overlaying the camera feed.

```yaml
type: picture-elements
camera_image: camera.p1s_camera
elements:
  - type: state-label
    entity: sensor.p1s_bed_temperature
    style:
      left: 50%
      top: 80%
      width: 100%
      text-align: center
      background-color: rgb(255,255,255,0.5)
    prefix: "Bed temperature: "
```

<img width="480" alt="Image" src="https://github.com/user-attachments/assets/354ff311-5f5b-4dde-b3be-e3a17d78155d" />
