### ISSUE TITLE
[Feature] Provide Cover/Preview Image through local LAN

### ISSUE THREAD

**Issue by chriswood1001** [greghesp/ha-bambulab#849]
### Describe the feature

Can the cover/preview image be pulled into Home Assistant via. local LAN, not cloud? I'm referring to the colored rendering of the product that's shown on the A1 screen during the print, not the camera entity.

Bambu's credential push leads me to believe that read-only values should be available over LAN. However this particular cover/preview image feature appears to be reliant on the cloud.

### What device is this for?

A1

**Comment by steveneaston** [comment]
I'm by no means a Python expert, but I've written a script that fetches the 3mf file from the printer's FTPS service using [ftplib](https://docs.python.org/3/library/ftplib.html) and extracts the primary thumbnail from it (if present).

To use it, download the bblab_fetch_image.py file from [this gist](https://gist.github.com/steveneaston/24f20e67429b72cc3aef1565f908a1f4) and run it with the printer's IP, LAN-mode access code and 3mf model name (in quotes if it has spaces):

```bash
python3 bblab_fetch_image.py 192.168.1.123 12345678 "My super model.3mf"
```

It'll export the image file to `./images/My super model.png`.

@greghesp @AdrianGarside I've got no idea how you'd go about implementing this into the plugin, or if you'd even want to but please use this script if it helps.

**Comment by AdrianGarside** [comment]
My concern is whether that would cause problems. Certainly early on after they introduced the FTPs support on the P1 printers it was always a gamble to download timelapses while printing as it might hang the printer (fans going, full temperature) in the middle of the print.

**Comment by t3chguy** [comment]
Might be good to have as an opt-in option anyway, I'd expect a 3mf file to be peanuts to transfer compared to a timelapse, and could be done during the initial heating/print readying.

**Comment by Woodcat64** [comment]
This would be welcome addition.

https://github.com/steveneaston Excuse my ignorance. Could HA add-on AppDaemon or the pyscript integration run your script?

**Comment by steveneaston** [comment]
@Woodcat64 I tried using pyscript but I couldn't work out how to register the FTP_TLS class, my Python isn't so good. However, you can do it just using the [shell_command](https://www.home-assistant.io/integrations/shell_command/) integration instead.

---

1. Take my [gist](https://gist.github.com/steveneaston/24f20e67429b72cc3aef1565f908a1f4)
2. Edit the last two lines:
    _Replace `models` with `www/bblab/models` and `images` with `www/bblab/images`_
    ```diff
    -download_model(host=printer_ip, access_code=access_code, model=model_name, download_path='models')
    -extract_image(f'models/{model_name}', extract_path='images')
    +download_model(host=printer_ip, access_code=access_code, model=model_name, download_path='www/bblab/models')
    +extract_image(f'www/bblab/models/{model_name}', extract_path='www/bblab/images')
    ```
3. Put the modified script into your HA config directory
4. Add the shell command to `configuration.yaml`
    ```yaml
    shell_command:
        bblab_image_getter: "python bblab_fetch_image.py {{ printer }} {{ access_code }} \"{{ model }}\""
    ```
5. In your template, use a Markdown card to render the image
    _(Replace `p1s` with your printer)_
    ```yaml
    type: markdown
    content: >-
      ![Image](/local/bblab/images/{{ states('sensor.p1s_gcode_filename') |
      regex_replace(find='3mf', replace='png') | urlencode }})
    ```
6. Trigger the shell command using an automation, I'm using a change to the `gcode_filename` sensor.
    ```yaml
    action: shell_command.bblab_image_getter
    data:
      printer: 192.168.1.123
      access_code: 12345678
      model: "{{ states('sensor.p1s_gcode_filename') }}"
    ````

**Comment by Woodcat64** [comment]
[@steveneaston](https://github.com/steveneaston) I got it mostly working. The issue is the markdown card does not show the image until I refresh firefox tab (didn't try the HA app yet). I will play with it when I have more time.

Thanks so much!

**Comment by steveneaston** [comment]
> The issue is the markdown card does not show the image until I refresh firefox tab (didn't try the HA app yet).

@Woodcat64 Unfortunately the markdown card isn't the best choice because it appears to not be reactive to changes. I also found it works in the companion app on the _external_ URL but not the internal URL. With that, there's two options.

**Simple option**: Output a static file
1. Replace this line:
    ```diff
    -image.filename = f'{os.path.splitext(model_filename)[0]}{os.path.splitext(image.filename)[1]}'
    +image.filename = 'model.png'
    ```
2. Use a picture card
   ```yaml
   type: picture
   image: /local/bblab/images/model.png
   ```

**Better option**: Use media-source
1. Set up a media source if you haven't already ([documentation](https://www.home-assistant.io/more-info/local-media/setup-media/))
2. Replace `www` in the output paths of the fetch script ([step 2 here](https://github.com/greghesp/ha-bambulab/issues/849#issuecomment-2612276079)) with the media-source name
3. Install the [Media Source Image](https://github.com/luixal/lovelace-media-source-image-card) card from HACS
4. Add it to your template
    _(Replace `p1s` with your printer, and `/media/` with the media source dir you set up in 1.)_
    ```yaml
    type: custom:media-source-image-card
    entity_id: sensor.p1s_gcode_filename
    image: >-
      media-source://media_source/media/bblab/images/{{
      states('sensor.p1s_gcode_filename') | regex_replace('3mf', 'png') }}
    # Remove the following if not using a Sections layout
    visibility:
      - condition: state
        entity: sensor.p1s_gcode_filename
        state_not: unknown
    ```
