### ISSUE TITLE
WLED integration

### ISSUE THREAD

**Issue by robinkesting** [greghesp/ha-bambulab#852]
I just watched Everything Smart Home and he showed a blueprint for connecting your Bambu integration with WLED. It seems it is not available in the repo anymore. Can I find it anywhere else? I use the integration for my printer and love it. Thanks!

**Comment by jneilliii** [comment]
the integration wasn't being maintained so it was stripped from the integration. I personally didn't like some of the choices and just made my own custom automations, it's not too difficult, and was able to create this. 

https://github.com/user-attachments/assets/ad7d6df6-fd42-45cd-9342-c4263dad7415

here's a less complicated one for just print completion for example that turns the effect to blink, sets the color and brightness, waits 5 minutes and then changes the effect again. 

```yaml
alias: Bambu Print Complete
description: ""
triggers:
  - device_id: 3866e9683e87891f3acb3ecde7b884d9
    domain: bambu_lab
    type: event_print_finished
    trigger: device
conditions: []
actions:
  - target:
      entity_id: light.wled
    data:
      rgb_color:
        - 17
        - 146
        - 32
      effect: Blink
      brightness_pct: 50
    action: light.turn_on
  - device_id: 6725c990eed08ca9161eb9ce82c7ed8c
    domain: number
    entity_id: a947f7cdc36f1e382d6f362682855536
    type: set_value
    value: 127
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - target:
      device_id: 6725c990eed08ca9161eb9ce82c7ed8c
    data:
      effect: Distortion Waves
      brightness_pct: 20
    action: light.turn_on
  - device_id: 6725c990eed08ca9161eb9ce82c7ed8c
    domain: number
    entity_id: a947f7cdc36f1e382d6f362682855536
    type: set_value
    value: 127
mode: single
```
