### ISSUE TITLE
[Bug] Bambu Lab AMS Card (vector) not handling negative values

### ISSUE THREAD

**Issue by gcs8** [greghesp/ha-bambulab#963]
### Home Assistant Version

2025.2.1

### Bambu Lab Integration Version

v2.1.1-beta1

### Describe the bug

Looks like it's not handling negative values as will as it could and wrapping back around to 100%, at least visually. 

![Image](https://github.com/user-attachments/assets/706427ac-805d-4ccc-9b46-6b1d4d971776)

### To Reproduce

use the last bit of the spool? 

### Expected Behaviour

if negative number report 0% or negative number. 

### What device are you using?

P1S

### Diagnostic Output

```shell
attached below
```

### Log Extracts

```shell

```

### Other Information

[config_entry-bambu_lab-01JA4K75DHFZ3DD9D3F42CBD5J (5).json](https://github.com/user-attachments/files/18735212/config_entry-bambu_lab-01JA4K75DHFZ3DD9D3F42CBD5J.5.json)
[config_entry-bambu_lab-01JA4K75DHFZ3DD9D3F42CBD5J (4).json](https://github.com/user-attachments/files/18735214/config_entry-bambu_lab-01JA4K75DHFZ3DD9D3F42CBD5J.4.json)
[config_entry-bambu_lab-01JA4K75DHFZ3DD9D3F42CBD5J (3).json](https://github.com/user-attachments/files/18735213/config_entry-bambu_lab-01JA4K75DHFZ3DD9D3F42CBD5J.3.json)

**Comment by gcs8** [comment]
![Image](https://github.com/user-attachments/assets/111c41b8-113f-46c7-b62a-216fb9e67b72)

**Comment by gcs8** [comment]
@greghesp I am the hellen keller of code, but this is what I did for my version of the AMS stats thing. 

```yaml
type: custom:button-card
entity: sensor.p1s_01p00c470401372_ams_1_tray_1
icon: mdi:printer-3d-nozzle
name: |
  [[[
    let tray = "Tray 1";
    let filamentType = states['sensor.p1s_01p00c470401372_ams_1_tray_1'].attributes.type || 'Unknown Type';
    return tray + " | " + filamentType;
  ]]]
show_icon: true
show_name: true
custom_fields:
  filament_name: |
    [[[
      return states['sensor.p1s_01p00c470401372_ams_1_tray_1'].attributes.name || 'Unknown Filament';
    ]]]
  status: |
    [[[
      let percentage = parseFloat(states['sensor.p1s_01p00c470401372_ams_1_tray_1'].attributes.remain) || 0;
      let remainingMeters = (percentage / 100) * 335;
      return percentage.toFixed(1) + '% | ' + remainingMeters.toFixed(1) + 'm';
    ]]]
styles:
  card:
    - height: 130px
    - font-size: 12px
    - background-color: |
        [[[
          return states['sensor.p1s_01p00c470401372_ams_1_tray_1'].attributes.active ? 'green' : 'var(--card-background-color)';
        ]]]
  grid:
    - grid-template-areas: "\"i\" \"n\" \"filament_name\" \"status\""
    - grid-template-rows: auto auto auto auto
    - grid-template-columns: 1fr
  custom_fields:
    filament_name:
      - justify-self: center
      - font-size: 12px
      - font-weight: bold
      - color: var(--primary-text-color)
      - white-space: normal
      - text-align: center
      - overflow: hidden
  status:
    - justify-self: center
    - font-size: 10px
    - color: var(--primary-text-color)
  icon:
    - color: |
        [[[
          return states['sensor.p1s_01p00c470401372_ams_1_tray_1'].attributes.color || '#FFFFFF';
        ]]]
```
