### ISSUE TITLE
[Bug] AMS card doesn't scale vertically when scaled horizontally

### ISSUE THREAD

**Issue by Ali229** [greghesp/ha-bambulab#965]
### Bug

I have two printers setup that take up half the space of the full width of a card:

But in the new AMS card when I do this the card doesn't scale vertically to reduce the height and look elongated:

<img src="https://github.com/user-attachments/assets/d6af93e5-25d3-45b6-938a-a436b17b126f" width="500" />

### What device is this for?

X1C

**Comment by Ali229** [comment]
Sure. This is the whole card, first thing in the card is the new AMS card.
```
type: custom:vertical-stack-in-card
cards:
  - type: custom:ha-bambulab-ams-card
    entity: ""
    header: ""
    subtitle: ""
    style: vector
    ams: "<AMS_ID>"
  - type: picture-elements
    view_layout:
      column: 1
    elements:
      - type: custom:config-template-card
        entities:
          - sensor.<unique_sensor_1>
        element:
          type: state-icon
          entity: sensor.<unique_sensor_1>
          icon: >-
            ${states['sensor.<unique_sensor_1>'].state != 'Empty'
            ? 'mdi:printer-3d-nozzle' : 'mdi:tray' }
        style:
          top: 28%
          left: 21.4%
          "--paper-item-icon-color": var(--tray_1_color)
          background-color: rgba(0,0,0,0.5)
          box-shadow: 0 0 4px 4px var(--tray_1_bg)
          border-radius: 50px
          "--mdc-icon-size": 2.4em
      - type: custom:config-template-card
        entities:
          - sensor.<unique_sensor_2>
        element:
          type: state-icon
          entity: sensor.<unique_sensor_2>
          icon: >-
            ${states['sensor.<unique_sensor_2>'].state != 'Empty'
            ? 'mdi:printer-3d-nozzle' : 'mdi:tray' }
        style:
          top: 28%
          left: 39.7%
          "--paper-item-icon-color": var(--tray_2_color)
          background-color: rgba(0,0,0,0.5)
          box-shadow: 0 0 4px 4px  var(--tray_2_bg)
          border-radius: 50px
          "--mdc-icon-size": 2.4em
      - type: custom:config-template-card
        entities:
          - sensor.<unique_sensor_3>
        element:
          type: state-icon
          entity: sensor.<unique_sensor_3>
          icon: >-
            ${states['sensor.<unique_sensor_3>'].state != 'Empty'
            ? 'mdi:printer-3d-nozzle' : 'mdi:tray' }
        style:
          top: 28%
          left: 59.7%
          "--paper-item-icon-color": var(--tray_3_color)
          background-color: rgba(0,0,0,0.5)
          box-shadow: 0 0 4px 4px  var(--tray_3_bg)
          border-radius: 50px
          "--mdc-icon-size": 2.4em
      - type: custom:config-template-card
        entities:
          - sensor.<unique_sensor_4>
        element:
          type: state-icon
          entity: sensor.<unique_sensor_4>
          icon: >-
            ${states['sensor.<unique_sensor_4>'].state != 'Empty'
            ? 'mdi:printer-3d-nozzle' : 'mdi:tray' }
        style:
          top: 28%
          left: 79.6%
          "--paper-item-icon-color": var(--tray_4_color)
          background-color: rgba(0,0,0,0.5)
          box-shadow: 0 0 4px 4px var(--tray_4_bg)
          border-radius: 50px
          "--mdc-icon-size": 2.4em
      - type: conditional
        conditions:
          - entity: sensor.<print_status_sensor>
            state_not: offline
        elements:
          - type: image
            style:
              width: 26.5%
              top: 90%
              left: 73.3%
            image: /local/media/ams_sensor.png
          - entity: sensor.<humidity_sensor>
            type: state-label
            style:
              top: 68%
              left: 74%
              font-size: 1.1vh
              color: black
              font-weight: bold
              font-family: Digifacewide
          - entity: sensor.<temperature_sensor>
            type: state-label
            style:
              top: 80%
              left: 74%
              font-size: 1.1vh
              color: black
              font-weight: bold
              font-family: Digifacewide
    image: /local/media/AMS_2.png
    card_mod:
      style: |
        ha-card {
          border: none;
          --tray_1_color:{% if is_state_attr('sensor.<unique_sensor_1>', 'empty', true) %}rgb(3, 169, 254){% else %}{{state_attr('sensor.<unique_sensor_1>', 'color')}}{% endif %};
          --tray_2_color:{% if is_state_attr('sensor.<unique_sensor_2>', 'empty', true) %}rgb(3, 169, 254){% else %}{{state_attr('sensor.<unique_sensor_2>', 'color')}}{% endif %};
          --tray_3_color:{% if is_state_attr('sensor.<unique_sensor_3>', 'empty', true) %}rgb(3, 169, 254){% else %}{{state_attr('sensor.<unique_sensor_3>', 'color')}}{% endif %};
          --tray_4_color:{% if is_state_attr('sensor.<unique_sensor_4>', 'empty', true) %}rgb(3, 169, 254){% else %}{{state_attr('sensor.<unique_sensor_4>', 'color')}}{% endif %};
          --tray_1_bg: {% if is_state_attr('sensor.<unique_sensor_1>', 'active', true) %} rgba(255, 255, 126, 0.5); {% else %} rgba(0,0,0,0.5); {% endif %}
          --tray_2_bg: {% if is_state_attr('sensor.<unique_sensor_2>', 'active', true) %} rgba(255, 255, 126, 0.5); {% else %} rgba(0,0,0,0.5); {% endif %}
          --tray_3_bg: {% if is_state_attr('sensor.<unique_sensor_3>', 'active', true) %} rgba(255, 255, 126, 0.5); {% else %} rgba(0,0,0,0.5); {% endif %}
          --tray_4_bg: {% if is_state_attr('sensor.<unique_sensor_4>', 'active', true) %} rgba(255, 255, 126, 0.5); {% else %} rgba(0,0,0,0.5); {% endif %}
        }
  - type: picture-elements
    view_layout:
      column: 1
    elements:
      - type: conditional
        conditions:
          - entity: sensor.<print_status_sensor>
            state_not: offline
        elements:
          - entity: sensor.<print_status_sensor>
            type: state-label
            style:
              top: 6%
              left: 33.3%
              font-size: 1.1vh
              color: rgb(186, 186, 186)
          - type: conditional
            conditions:
              - entity: sensor.<print_status_sensor>
                state: running
            elements:
              - entity: sensor.<time_left_sensor>
                type: state-label
                style:
                  top: 12%
                  left: 33.3%
                  font-size: 1.1vh
                  color: rgb(186, 186, 186)
              - entity: sensor.<task_name_sensor>
                type: state-label
                style:
                  top: 93%
                  left: 51%
                  font-size: 0.9vh
                  color: black
          - entity: sensor.<nozzle_temperature_sensor>
            type: state-badge
            style:
              top: 40%
              left: 51%
              font-size: 0.5em
              color: rgba(0,0,0,0)
          - entity: sensor.<bed_temperature_sensor>
            type: state-badge
            style:
              top: 83%
              left: 51%
              font-size: 0.5em
              color: rgba(0,0,0,0)
    card_mod:
      style: |
        ha-card {
          border: none;
        }
    image: /local/media/bambuprinter/on_lighton_2.png
    entity: light.<chamber_light_sensor>
    state_image:
      unavailable: /local/media/bambuprinter/off.png
      "on": /local/media/bambuprinter/off.png
      "off": /local/media/bambuprinter/off.png
  - type: conditional
    conditions:
      - entity: sensor.<print_status_sensor>
        state: running
    card:
      type: custom:bar-card
      positions:
        icon: "off"
        name: "off"
        indicator: "off"
      height: 25px
      card_mod:
        style: |
          ha-card {
            padding: 0px 13px 5px 18px; 
            border: none;
          }
          bar-card-value {
            margin: auto;
          }
          bar-card-currentbar, bar-card-backgroundbar {
            border-radius: 5px;
          }
      entity_row: true
      entities:
        - entity: sensor.<print_progress_sensor>

```

**Comment by Ali229** [comment]
To reproduce simply adding the ams card to a vertical stack resizing the stack horizontally works:
```
type: vertical-stack
cards:
  - type: custom:ha-bambulab-ams-card
    style: vector
    ams: my_ams_id
grid_options:
  columns: 6
  rows: auto
```
